### ISSUE TITLE
Can't change snapping properties all the time

### ISSUE THREAD

**Issue by redorav** [vaspoul/render.diagrams#43]
If I add a line I can change the snapping before I click, but after clicking once, the property panel changes to the line properties. Same thing happens to all the objects like circles, etc. I think the snapping properties should remain until after I've finished drawing the figure. I should mention the snapping can be changed via the keyboard shortcuts, if you're good enough to memorize them.

**Comment by vaspoul** [comment]
New UI shows the snap controls all the time (and shows the keyboard shortcuts too)
